### ISSUE TITLE
Responsoria Septuaginta - Sexaginta - Quinquagesima

### ISSUE THREAD

**Issue by Avika1804** [marekklein/transcriptions#30]
Till now I don’t understand completely how are organised Sexagesima and quinquagesima (for resp/readings), but starting with septuagesima in safe.
Courage, from Easter it will be easier…

THANKS,

Isabelle

In Septuagesima

01. In principio Deus creavit caelum et terram: we have Joppich (maybe we should adapt square notes for maching neums closer)
02. In principio creavit Deus … et fecit https://gregobase.selapa.net/chant.php?id=9610
03. Formavit Dominus hominem https://gregobase.selapa.net/chant.php?id=9611

04 Tulit ergo DOminus https://gregobase.selapa.net/chant.php?id=9612
05. Dixit Dominus Deus https://gregobase.selapa.net/chant.php?id=9613
06. Immisit Dominus soporem https://gregobase.selapa.net/chant.php?id=9614

07. Dum deambularet Dominus https://gregobase.selapa.net/chant.php?id=9615
08 In sudore vultus tui https://gregobase.selapa.net/chant.php?id=9616
09. Ecce Adam quasi unus https://gregobase.selapa.net/chant.php?id=9617

10. Ubi est Abel frater tuus https://gregobase.selapa.net/chant.php?id=9618

In Sexagesima

01. Quadraginta dies et noctes https://gregobase.selapa.net/chant.php?id=9619
02. Ponam arcum meum in nubibus.  https://gregobase.selapa.net/chant.php?id=9620
03. Per memetipsum iuravi https://gregobase.selapa.net/chant.php?id=9622

04. Aedifcavit Noe altare https://gregobase.selapa.net/chant.php?id=9623

In Quinquagesima

05 Locutus est Dominus ad Abram https://gregobase.selapa.net/chant.php?id=9624
12. Dum staret Abraham
06 Tentavit Deus Abraham https://gregobase.selapa.net/chant.php?id=9625

07 Angelus Domini vocavit https://gregobase.selapa.net/chant.php?id=9626
08 Vocavit angelus Domini https://gregobase.selapa.net/chant.php?id=9627
09 Deus Domini mei Abraham https://gregobase.selapa.net/chant.php?id=9628

10 Veni hodie https://gregobase.selapa.net/chant.php?id=9629
11 Caecus sedebat https://gregobase.selapa.net/chant.php?id=9630

**Comment by marekklein** [comment]
Hi Isabelle,
for septuagessima there is 
08 In sudore vultus tui https://gregobase.selapa.net/chant.php?id=9616 
and also 
8 Ecce Adam quasi unus https://gregobase.selapa.net/chant.php?id=9617
Should there be 9 responsories, or 10?

**Comment by Avika1804** [comment]
Hi Marek!

For Sunday, 6, but we well sing the other ones during the week, so as
many as possible...
THANKS

2021-01-29 10:31 UTC+01:00, Marek Klein <notifications@github.com>:
